language: generic
os: linux
services: docker
branches:
  only:
  - master
env:
  global:
  - PROJECT_NAME=lpp-parser
  - PROJECT_VERSION=1.0.13
  - DOCKER_USERNAME=bezpov
  - secure: rORtx9nhTIYBq5GBZhQnsL3hLO2I/QT+P16vzvucxo9nnNl1JG9BPU0ZHfkB03REWS5gsTCzhAy3NCOrziPXpGd7sqmlb8KceQgBvKa4kul42KTYyf5aVQt9gFUHUrC4hEsni3eHItqawI1pF+NKnVyU1cSN8vO68ywVtekT0wRie5L9l3Ofta/IcMrTz1F34pEydjLvVnGMB1TjaTPf7YpI7WTRXiv0eRZnEqcZlkYLuOuq7QTo8A0wtRDRfrgsIorQE7qnGGrGiKDiAI9pvQfCVSa6WeFVZ0XnH6J5aKpqLFT9+aRdFz8tB4/qSdZi8Q9ZpFm4n98JM4oWm8GGvVPqsO9L9wJXfU1kad6CYiDAxyBghQnLrxjar7BXkTYP2qYnS53hhAOPB9+9QLzQ027EHo4/20QuyIYZBtkKK8bTRmWSROdmyPSHb7M5yBxdlwbkd6RKE3BfKI6M/VORK26WF4Jpo5TRVgthL9TMal3BcrmkztQXVHPfrH9CiIqtXtxImDdL9sTd+4LNsHVIXUorK5tqHw5V7yCB8tRQJxg+RsILKIwFTuJw+XmP21asoGl7IWE1mSzNgrKqTzNDc9StcRgAORyP0qoGmMWHO9RsdMwdBLWl0+c2+811k3vKzQLGOYBKo5EJsDvWRC5z5XWzBeb6DJwNweJrZp1BjNs=
  - secure: b+tSU6v0JBEmfP5Owc14R3rL0+TMPXq3q++h2hmauV6ZQNLkK3MDb5selfrbqhWZ5jHcBUm8dYC02ej3vHxFbxZ2D1XQPjk1fAInLTrRhXkeyrqAtS97AuPccKpqO5TCKbv/JcdovD2z8BM08Y0UfOAlDqDjkCoCW09swWvYy/A8e0tW1GXF7mlQxABnnSOndUDoPl4qmV6SEZX5J6MFnRuWQ6F0Q/weqJH4Wzo2rCb9q00zn3NKAs4KlVdXv/0a8geQRlPM8xgFczgn1L6/5/3jC6Uz4Ttk0T26twgGc+HVzLdyqBkSoeZCe07u/l3nfxb52rq7nqH1mVdKRWlU1fD/03wun6cd/Z+guCzSwgF7GSoBjw2Za0mB0fCkyI573yoxB2q5hnOsyA6N2o2m84p/dEnbYVScuxni8GvfJw3AlSvhiOFvtS+zQKI+uwpJCMKHZFWR8zRQ6E5wBe2oh4Tpuwu//DkBhCvpq8zug74LpdYGrmIiNrHbBY6/BR+L55PTYA8DIfEzNYcspBxwylVVVIpTNlpmO+zmWuRYBHzW/9v5oezOIeUSX5iXOSn2PCBmdssteZdqrwfhd2jDp0sB3qaw9YxTlGCWn9PA3UASd9gE9HXt5R3gzFEIo3hBfgsdM/sN33iR2eCY+gJH7BvEnwrYG4YP7Fg5Hh9WJRE=
before_install:
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/google-travis-service-account.json.gpg
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file ./config/google-travis-service-account.json
- gcloud config set project massive-boulder-263710
- gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
- gcloud components install kubectl
- kubectl apply -f ./kubernetes/deployment.yaml
