language: javascript
services: docker
env:
  global:
  - PROJECT_NAME=lpp-parser
  - PROJECT_VERSION=1.0.0
  - DOCKER_USERNAME=bezpov
  - secure: rORtx9nhTIYBq5GBZhQnsL3hLO2I/QT+P16vzvucxo9nnNl1JG9BPU0ZHfkB03REWS5gsTCzhAy3NCOrziPXpGd7sqmlb8KceQgBvKa4kul42KTYyf5aVQt9gFUHUrC4hEsni3eHItqawI1pF+NKnVyU1cSN8vO68ywVtekT0wRie5L9l3Ofta/IcMrTz1F34pEydjLvVnGMB1TjaTPf7YpI7WTRXiv0eRZnEqcZlkYLuOuq7QTo8A0wtRDRfrgsIorQE7qnGGrGiKDiAI9pvQfCVSa6WeFVZ0XnH6J5aKpqLFT9+aRdFz8tB4/qSdZi8Q9ZpFm4n98JM4oWm8GGvVPqsO9L9wJXfU1kad6CYiDAxyBghQnLrxjar7BXkTYP2qYnS53hhAOPB9+9QLzQ027EHo4/20QuyIYZBtkKK8bTRmWSROdmyPSHb7M5yBxdlwbkd6RKE3BfKI6M/VORK26WF4Jpo5TRVgthL9TMal3BcrmkztQXVHPfrH9CiIqtXtxImDdL9sTd+4LNsHVIXUorK5tqHw5V7yCB8tRQJxg+RsILKIwFTuJw+XmP21asoGl7IWE1mSzNgrKqTzNDc9StcRgAORyP0qoGmMWHO9RsdMwdBLWl0+c2+811k3vKzQLGOYBKo5EJsDvWRC5z5XWzBeb6DJwNweJrZp1BjNs=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
